version: 2.1

executors:
  ci-executor:
    docker:
      - image: douggernaut/threeagent-ci:0.0.1
    working_directory: ~/app
    resource_class: small

orbs:
  changelog: onimur/github-changelog-generator@2.1.9

jobs:
  test:
    executor: ci-executor
    working_directory: ~/app/test/browser_test
    steps:
      - checkout:
          path: ~/app
      - restore_cache:
          keys:
            - npm-browser-test-{{ checksum "package-lock.json" }}
            - mvn-browser-test-{{ checksum "shadow-cljs.edn" }}
      - run: npm ci
      - save_cache:
          key: npm-browser-test-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Building cljs
          command: npx shadow-cljs compile ci
      - save_cache:
          key: mvn-browser-test-{{ checksum "shadow-cljs.edn" }}
          paths:
            - "~/.m2"
      - run:
          name: Running karma tests
          command: npx karma start --single-run
      - store_test_results:
          path: reports

  deploy_snapshot:
    executor: ci-executor
    steps:
      - checkout
      - run:
          name: Deploying to clojars
          command: lein deploy

  release:
    executor: ci-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a6:26:0e:aa:89:d1:db:6c:5b:26:bb:46:d2:2d:21:59"
      - checkout
      - run:
          name: Git Config
          command: |
            git config --global user.email "no-reply@circleci.com"
            git config --global user.name "CircleCI Release Script"
            git remote set-url origin https://github.com/DougHamil/threeagent-asset-loader.git
      - run:
          name: Release rc
          command: lein release :patch

workflows:
  changelog:
    jobs:
      - changelog/changelog-default:
          context:
            - clojars
          pre-steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                  - "a6:26:0e:aa:89:d1:db:6c:5b:26:bb:46:d2:2d:21:59"
          branch: main
          commit-message: "Update CHANGELOG"
          git-push: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/

  build-test-publish:
    jobs:
      - test
      - deploy_snapshot:
          context:
            - clojars
          filters:
            branches:
              only:
                - "main"
          requires:
            - test

      - hold:
          filters:
            branches:
              only: /^release$/
          type: approval
          requires:
            - test

      - release:
          context:
            - clojars
          filters:
            branches:
              only: /^release$/
          requires:
            - hold
